import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { FakeAssistant, completed, defaultSynthesis } from "./support/fake-assistant.ts";
import { description, processApi, statement } from "./support/process-api.ts";
import { TEST_MODEL, createTestApp, resetDatabase, type TestApp } from "./support/test-app.ts";

let assistant: FakeAssistant;
let testApp: TestApp;
const api = processApi(() => testApp);

beforeEach(async () => {
  assistant = new FakeAssistant();
  testApp = await createTestApp({ assistant });
  await resetDatabase(testApp.db);
});

afterEach(async () => {
  await testApp.close();
});

describe("Block synthesis", () => {
  it("is generated by the AI from the Block's answers and shown as a suggestion, with the coverage it suggests", async () => {
    const { id, block } = await api.processWithAnsweredBlock();

    const response = await api.requestSynthesis(id, block.id);

    expect(response.statusCode).toBe(202);
    expect(response.json().synthesisRequest).toMatchObject({ status: "running", proposal: null });
    const settled = await api.settledSynthesis(id, block.id);
    const [single, multiple, free] = block.questions;
    expect(assistant.synthesis.attempts[0]!.input).toEqual({
      stage: "P",
      originalDescription: description,
      problemStatement: statement,
      // Na Etapa P, nenhuma Etapa confirmada antes.
      confirmedStages: [],
      openStagePoints: (await api.getProcess(id)).openStagePoints,
      blockNumber: 1,
      questions: [
        { ref: "1.1", wording: single.wording, stagePoints: ["real_problem"], answer: single.choices[0], unknown: false },
        { ref: "1.2", wording: multiple.wording, stagePoints: ["consequence", "urgency"], answer: multiple.choices[0], unknown: false },
        { ref: "1.3", wording: free.wording, stagePoints: ["urgency"], answer: "A diretoria cobrou na última reunião.", unknown: false },
      ],
      earlierQuestions: [],
    });
    expect(assistant.synthesis.attempts[0]!.context.model).toBe(TEST_MODEL);
    expect(settled.synthesis).toBeNull();
    expect(settled.synthesisRequests).toMatchObject([
      {
        status: "completed",
        attempts: [{ number: 1, status: "completed", model: TEST_MODEL }],
        proposal: {
          id: settled.synthesisRequests[0].attempts[0].id,
          synthesis: defaultSynthesis.synthesis,
          coverage: [
            { stagePoint: { key: "real_problem", name: "Problema real versus sintoma" }, covered: true, reason: expect.any(String) },
            { stagePoint: { key: "consequence", name: "Consequência de não resolver" }, covered: true, reason: expect.any(String) },
            { stagePoint: { key: "urgency", name: "Motivo da urgência" }, covered: false, reason: expect.any(String) },
          ],
          ambiguousAnswers: [],
          outdated: false,
        },
      },
    ]);
    // A sugestão não cobre nada: os Pontos seguem abertos até a Confirmação.
    const process = await api.getProcess(id);
    expect(process.openStagePoints.map((point: { key: string }) => point.key)).toEqual(["real_problem", "consequence", "urgency"]);
  });

  it("confirmed as the AI proposed covers only the Points the user confirms, and confirms the Block's answers together", async () => {
    const { id, block } = await api.processWithAnsweredBlock();
    const proposal = await api.synthesize(id, block.id);
    // Antes da Confirmação, as respostas do Bloco são provisórias.
    expect((await api.blockOf(id, block.id)).questions.map((question: { answer: { current: { confirmed: boolean } } }) => question.answer.current.confirmed)).toEqual([false, false, false]);

    const response = await api.confirmSynthesis(id, block.id, {
      proposalId: proposal.id,
      synthesis: proposal.synthesis,
      coveredStagePoints: ["real_problem"],
    });

    expect(response.statusCode).toBe(201);
    expect(response.json().synthesis).toEqual({
      synthesis: defaultSynthesis.synthesis,
      origin: "proposal",
      proposalId: proposal.id,
      confirmedAt: expect.any(String),
      coveredStagePoints: [{ key: "real_problem", name: "Problema real versus sintoma" }],
    });
    const process = await api.getProcess(id);
    // A IA sugeriu também "consequence"; sem Confirmação, ele segue aberto.
    expect(process.openStagePoints.map((point: { key: string }) => point.key)).toEqual(["consequence", "urgency"]);
    expect(process.stagePoints).toMatchObject([
      { key: "real_problem", status: "covered", blockId: block.id, justification: null },
      { key: "consequence", status: "open", blockId: null },
      { key: "urgency", status: "open", blockId: null },
    ]);
    const confirmed = process.blocks[0];
    expect(confirmed.synthesis).toEqual(response.json().synthesis);
    expect(confirmed.questions.map((question: { answer: { current: { confirmed: boolean } } }) => question.answer.current.confirmed)).toEqual([true, true, true]);
  });

  it("corrected by the user keeps the corrected text, and the AI proposal stays as it came", async () => {
    const { id, block } = await api.processWithAnsweredBlock();
    const proposal = await api.synthesize(id, block.id);
    const corrected = "A demora é sintoma de testes lentos; já atrasou entregas.";

    const response = await api.confirmSynthesis(id, block.id, {
      proposalId: proposal.id,
      synthesis: `  ${corrected}\n`,
      coveredStagePoints: ["real_problem", "consequence"],
    });

    expect(response.statusCode).toBe(201);
    expect(response.json().synthesis).toMatchObject({ synthesis: corrected, origin: "corrected" });
    const confirmedBlock = await api.blockOf(id, block.id);
    expect(confirmedBlock.synthesis).toMatchObject({ synthesis: corrected, origin: "corrected" });
    expect(confirmedBlock.synthesisRequests[0].proposal.synthesis).toBe(defaultSynthesis.synthesis);
    expect((await api.getProcess(id)).openStagePoints.map((point: { key: string }) => point.key)).toEqual(["urgency"]);
  });

  it("is not requested before every question of the Block is answered or declared unknown", async () => {
    const id = await api.createProcess();
    await api.confirmStatement(id);
    const block = await api.generateBlock(id);
    await api.answer(id, block.questions[0].id, { selectedChoices: [0], basedOnVersionId: null });

    const response = await api.requestSynthesis(id, block.id);

    expect(response.statusCode).toBe(409);
    expect(response.json()).toEqual({ error: "block_incomplete" });
    expect(assistant.synthesis.attempts).toHaveLength(0);
  });

  it("is refused for a Block of another Process", async () => {
    const other = await api.processWithAnsweredBlock();
    const id = await api.createProcess();

    const response = await api.requestSynthesis(id, other.block.id);

    expect(response.statusCode).toBe(404);
    expect(response.json()).toEqual({ error: "block_not_found" });
  });

  it("is not requested twice while its proposal still matches the answers", async () => {
    const { id, block } = await api.processWithAnsweredBlock();
    await api.synthesize(id, block.id);

    const response = await api.requestSynthesis(id, block.id);

    expect(response.statusCode).toBe(409);
    expect(response.json()).toEqual({ error: "synthesis_already_requested" });
  });

  it("whose answers changed after the proposal is outdated: it cannot be confirmed, and a new synthesis can be requested", async () => {
    const { id, block } = await api.processWithAnsweredBlock();
    const proposal = await api.synthesize(id, block.id);
    const [single] = (await api.blockOf(id, block.id)).questions;
    await api.answer(id, single.id, { selectedChoices: [1], basedOnVersionId: single.answer.current.id });

    const refused = await api.confirmSynthesis(id, block.id, {
      proposalId: proposal.id,
      synthesis: proposal.synthesis,
      coveredStagePoints: [],
    });

    expect(refused.statusCode).toBe(409);
    expect(refused.json()).toEqual({ error: "synthesis_outdated" });
    expect((await api.blockOf(id, block.id)).synthesisRequests[0].proposal.outdated).toBe(true);
    const renewed = await api.synthesize(id, block.id);
    expect(assistant.synthesis.attempts[1]!.input.questions[0]!.answer).toBe(single.choices[1]);
    const response = await api.confirmSynthesis(id, block.id, { proposalId: renewed.id, synthesis: renewed.synthesis, coveredStagePoints: [] });
    expect(response.statusCode).toBe(201);
    expect((await api.blockOf(id, block.id)).synthesisRequests).toHaveLength(2);
  });

  it("is confirmed only once", async () => {
    const { id, block } = await api.processWithAnsweredBlock();
    const proposal = await api.synthesize(id, block.id);
    const confirmation = { proposalId: proposal.id, synthesis: proposal.synthesis, coveredStagePoints: ["real_problem"] };
    await api.confirmSynthesis(id, block.id, confirmation);

    const response = await api.confirmSynthesis(id, block.id, confirmation);

    expect(response.statusCode).toBe(409);
    expect(response.json()).toEqual({ error: "synthesis_confirmed" });
    expect((await api.requestSynthesis(id, block.id)).json()).toEqual({ error: "synthesis_confirmed" });
  });

  it.each([
    ["a Point that is not of the Stage", ["deadline"]],
    ["a Point declared inapplicable", "covered"],
  ] as const)("is refused when covering %s", async (_case, covered) => {
    const { id, block } = await api.processWithAnsweredBlock();
    const proposal = await api.synthesize(id, block.id);
    if (covered === "covered") {
      expect((await api.declareInapplicable(id, "urgency", { justification: "Não há urgência; é melhoria contínua." })).statusCode).toBe(201);
    }

    const response = await api.confirmSynthesis(id, block.id, {
      proposalId: proposal.id,
      synthesis: proposal.synthesis,
      coveredStagePoints: covered === "covered" ? ["urgency"] : covered,
    });

    expect(response.statusCode).toBe(422);
    expect(response.json()).toEqual({ error: "invalid_coverage" });
    expect((await api.blockOf(id, block.id)).synthesis).toBeNull();
  });

  it("is refused for a proposal that is not the Block's", async () => {
    const { id, block } = await api.processWithAnsweredBlock();
    await api.synthesize(id, block.id);

    const response = await api.confirmSynthesis(id, block.id, {
      proposalId: "00000000-0000-4000-8000-000000000000",
      synthesis: "Texto",
      coveredStagePoints: [],
    });

    expect(response.statusCode).toBe(422);
    expect(response.json()).toEqual({ error: "unknown_synthesis" });
  });

  it.each([
    ["no text", { coveredStagePoints: [] }],
    ["blank text", { synthesis: "  ", coveredStagePoints: [] }],
    ["no list of covered Points", { synthesis: "Texto" }],
  ])("is refused when sent with %s", async (_case, payload) => {
    const { id, block } = await api.processWithAnsweredBlock();
    const proposal = await api.synthesize(id, block.id);

    const response = await api.confirmSynthesis(id, block.id, { proposalId: proposal.id, ...payload });

    expect(response.statusCode).toBe(400);
  });

  it("is refused when the AI suggests coverage outside the open Points, or leaves one without suggestion", async () => {
    const [first, ...rest] = defaultSynthesis.coverage;
    assistant.synthesis.willRespond(
      completed({ ...defaultSynthesis, coverage: [{ ...first!, stagePoint: "deadline" }, ...rest] }),
      completed({ ...defaultSynthesis, coverage: rest }),
    );
    const { id, block } = await api.processWithAnsweredBlock();
    await api.requestSynthesis(id, block.id);
    const failed = await api.settledSynthesis(id, block.id);
    expect(failed.synthesisRequests).toMatchObject([
      { status: "failed", proposal: null, attempts: [{ failureReason: "invalid_output", message: expect.stringContaining("deadline") }] },
    ]);

    await api.newSynthesisAttempt(id, block.id, failed.synthesisRequests[0].id);

    const missing = await api.settledSynthesis(id, block.id);
    expect(missing.synthesisRequests[0].attempts[1]).toMatchObject({ failureReason: "invalid_output", message: expect.stringContaining("real_problem") });
  });

  it("is not generated when the AI fails, and a new attempt of the same request generates it", async () => {
    assistant.synthesis.willRespond({ status: "timed_out" });
    const { id, block } = await api.processWithAnsweredBlock();
    await api.requestSynthesis(id, block.id);
    const failed = await api.settledSynthesis(id, block.id);
    expect((await api.requestSynthesis(id, block.id)).json()).toEqual({ error: "synthesis_already_requested" });

    const response = await api.newSynthesisAttempt(id, block.id, failed.synthesisRequests[0].id);

    expect(response.statusCode).toBe(202);
    const settled = await api.settledSynthesis(id, block.id);
    expect(settled.synthesisRequests).toHaveLength(1);
    expect(settled.synthesisRequests[0].attempts.map((attempt: { status: string }) => attempt.status)).toEqual(["timed_out", "completed"]);
    expect(settled.synthesisRequests[0].proposal).toMatchObject({ synthesis: defaultSynthesis.synthesis });
    expect((await api.newSynthesisAttempt(id, block.id, failed.synthesisRequests[0].id)).json()).toEqual({ error: "synthesis_generated" });
  });
});
