import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { sql } from "kysely";
import { FakeAssistant } from "./support/fake-assistant.ts";
import { TEST_MODEL, createTestApp, resetDatabase, waitFor, type TestApp } from "./support/test-app.ts";

let assistant: FakeAssistant;
let testApp: TestApp;

beforeEach(async () => {
  assistant = new FakeAssistant();
  testApp = await createTestApp({ assistant });
  await resetDatabase(testApp.db);
});

afterEach(async () => {
  await testApp.close();
});

const description = "Nosso deploy demora demais e o time perde a manhã.";
const statement = "O deploy leva 40 minutos e bloqueia o time durante a manhã.";

async function createProcess(): Promise<string> {
  const response = await testApp.app.inject({ method: "POST", url: "/api/processes", payload: { description } });
  expect(response.statusCode).toBe(201);
  return response.json().process.id;
}

async function getProcess(id: string, app = testApp) {
  const response = await app.app.inject({ method: "GET", url: `/api/processes/${id}` });
  expect(response.statusCode).toBe(200);
  return response.json().process;
}

describe("Stage Points", () => {
  it("are those of version 1 of the list, all still open in Stage P", async () => {
    const id = await createProcess();

    const process = await getProcess(id);

    expect(process.currentStage).toBe("P");
    expect(process.stagePointsVersion).toBe(1);
    expect(process.openStagePoints.map((point: { key: string; name: string }) => [point.key, point.name])).toEqual([
      ["real_problem", "Problema real versus sintoma"],
      ["consequence", "Consequência de não resolver"],
      ["urgency", "Motivo da urgência"],
    ]);
  });
});

async function confirmStatement(id: string) {
  const response = await testApp.app.inject({
    method: "POST",
    url: `/api/processes/${id}/problem-statement/confirmation`,
    payload: { statement },
  });
  expect(response.statusCode).toBe(201);
}

function requestBlock(id: string) {
  return testApp.app.inject({ method: "POST", url: `/api/processes/${id}/block-requests` });
}

// Espera a tentativa mais recente da última Solicitação de Bloco sair de "running".
async function settledBlockRequest(id: string) {
  let process: Awaited<ReturnType<typeof getProcess>>;
  await waitFor(async () => {
    process = await getProcess(id);
    const request = process.blockRequests.at(-1);
    return request !== undefined && request.status !== "running";
  });
  return process!;
}

describe("Block", () => {
  it("is generated by the AI for the open Points of Stage P, once the problem statement is confirmed", async () => {
    const id = await createProcess();
    await confirmStatement(id);

    const response = await requestBlock(id);

    expect(response.statusCode).toBe(202);
    expect(response.json().blockRequest).toMatchObject({ status: "running", blockId: null });
    const process = await settledBlockRequest(id);
    expect(assistant.block.attempts[0]!.input).toEqual({
      stage: "P",
      originalDescription: description,
      problemStatement: statement,
      openStagePoints: process.openStagePoints,
    });
    expect(assistant.block.attempts[0]!.context.model).toBe(TEST_MODEL);
    const [block] = process.blocks;
    expect(process.blockRequests).toMatchObject([{ status: "completed", blockId: block.id, attempts: [{ number: 1, model: TEST_MODEL }] }]);
    expect(block).toMatchObject({ number: 1, stage: "P" });
    expect(block.questions).toEqual([
      {
        id: expect.any(String),
        subject: "Sintoma ou causa",
        contextRelation: "O enunciado fala da demora do deploy, mas não do que a provoca.",
        rationale: "Separar o sintoma do problema real evita resolver a coisa errada.",
        stagePoints: [{ key: "real_problem", name: "Problema real versus sintoma" }],
        answerType: "single_choice",
        options: ["A demora é o problema em si", "A demora é sintoma de outra coisa", "Não sei"],
        answer: null,
        draft: null,
      },
      {
        id: expect.any(String),
        subject: "Efeitos da demora",
        contextRelation: "O time perde a manhã esperando o deploy.",
        rationale: null,
        stagePoints: [
          { key: "consequence", name: "Consequência de não resolver" },
          { key: "urgency", name: "Motivo da urgência" },
        ],
        answerType: "multiple_choice",
        options: ["Atraso nas entregas", "Horas extras", "Clientes reclamando"],
        answer: null,
        draft: null,
      },
      {
        id: expect.any(String),
        subject: "Por que agora",
        contextRelation: "O problema existe há algum tempo.",
        rationale: "A urgência define quanto esforço cabe agora.",
        stagePoints: [{ key: "urgency", name: "Motivo da urgência" }],
        answerType: "free_text",
        options: [],
        answer: null,
        draft: null,
      },
    ]);
  });

  it("is not requested before the problem statement is confirmed", async () => {
    const id = await createProcess();

    const response = await requestBlock(id);

    expect(response.statusCode).toBe(409);
    expect(response.json()).toEqual({ error: "problem_statement_not_confirmed" });
    expect((await getProcess(id)).blockRequests).toEqual([]);
    expect(assistant.block.attempts).toHaveLength(0);
  });

  it("is requested only once in this slice", async () => {
    const id = await createProcess();
    await confirmStatement(id);
    await requestBlock(id);

    const response = await requestBlock(id);

    expect(response.statusCode).toBe(409);
    expect(response.json()).toEqual({ error: "block_already_requested" });
    expect((await settledBlockRequest(id)).blocks).toHaveLength(1);
    expect(assistant.block.attempts).toHaveLength(1);
  });

  it.each([
    ["an unknown Process", "00000000-0000-4000-8000-000000000000"],
    ["a malformed id", "not-a-process"],
  ])("is refused for %s", async (_case, id) => {
    const response = await requestBlock(id);

    expect(response.statusCode).toBe(404);
    expect(assistant.block.attempts).toHaveLength(0);
  });

  it("is not generated when the AI fails, and a new attempt of the same request generates it", async () => {
    assistant.block.willRespond({ status: "failed", reason: "invalid_output", message: "fora do formato", usage: null });
    const id = await createProcess();
    await confirmStatement(id);
    await requestBlock(id);
    const failed = await settledBlockRequest(id);
    expect(failed.blockRequests).toMatchObject([{ status: "failed", blockId: null }]);
    expect(failed.blocks).toEqual([]);

    const response = await newBlockAttempt(id, failed.blockRequests[0].id);

    expect(response.statusCode).toBe(202);
    const process = await settledBlockRequest(id);
    expect(process.blockRequests).toMatchObject([
      { id: failed.blockRequests[0].id, status: "completed", blockId: process.blocks[0].id },
    ]);
    expect(process.blockRequests[0].attempts.map((attempt: { status: string }) => attempt.status)).toEqual(["failed", "completed"]);
    expect(process.blocks).toHaveLength(1);
  });

  it("refuses a new attempt once the Block was generated, so it is never duplicated", async () => {
    const id = await createProcess();
    await confirmStatement(id);
    await requestBlock(id);
    const { blockRequests } = await settledBlockRequest(id);

    const response = await newBlockAttempt(id, blockRequests[0].id);

    expect(response.statusCode).toBe(409);
    expect(response.json()).toEqual({ error: "block_generated" });
    expect((await getProcess(id)).blocks).toHaveLength(1);
  });

  it("refuses a new attempt while an attempt is running", async () => {
    assistant.block.willHold();
    const id = await createProcess();
    await confirmStatement(id);
    const { blockRequest } = (await requestBlock(id)).json();

    const response = await newBlockAttempt(id, blockRequest.id);

    expect(response.statusCode).toBe(409);
    expect(response.json()).toEqual({ error: "attempt_in_progress" });
  });

  it("refuses a new attempt of a request that is not this Process's", async () => {
    const other = await createProcess();
    await confirmStatement(other);
    assistant.block.willRespond({ status: "timed_out" });
    const { blockRequest } = (await requestBlock(other)).json();
    await settledBlockRequest(other);
    const id = await createProcess();
    await confirmStatement(id);

    const response = await newBlockAttempt(id, blockRequest.id);

    expect(response.statusCode).toBe(404);
    expect(response.json()).toEqual({ error: "block_request_not_found" });
  });

  it("that cannot be saved leaves the attempt interrupted, never completed without a Block", async () => {
    const id = await createProcess();
    await confirmStatement(id);
    await sql`create function probe_test_fail() returns trigger language plpgsql as
      $$ begin raise exception 'falha simulada do banco'; end $$`.execute(testApp.db);
    await sql`create trigger probe_test_fail before insert on questions
      for each row execute function probe_test_fail()`.execute(testApp.db);
    let process;
    try {
      await requestBlock(id);
      process = await settledBlockRequest(id);
    } finally {
      await sql`drop trigger probe_test_fail on questions`.execute(testApp.db);
      await sql`drop function probe_test_fail`.execute(testApp.db);
    }

    expect(process.blockRequests).toMatchObject([{ status: "interrupted", blockId: null }]);
    expect(process.blocks).toEqual([]);
    expect((await newBlockAttempt(id, process.blockRequests[0].id)).statusCode).toBe(202);
    expect((await settledBlockRequest(id)).blocks).toHaveLength(1);
  });

  it("shows as interrupted after the backend shuts down mid-attempt, with no Block", async () => {
    assistant.block.willHold();
    const id = await createProcess();
    await confirmStatement(id);
    await requestBlock(id);
    await waitFor(() => assistant.block.attempts.length === 1);

    await testApp.close();
    testApp = await createTestApp({ assistant });

    const process = await getProcess(id);
    expect(process.blockRequests).toMatchObject([{ status: "interrupted", blockId: null }]);
    expect(process.blocks).toEqual([]);
  });
});

function newBlockAttempt(id: string, requestId: string) {
  return testApp.app.inject({ method: "POST", url: `/api/processes/${id}/block-requests/${requestId}/attempts` });
}

// Processo com o enunciado confirmado e o primeiro Bloco gerado (o padrão do Assistant falso:
// alternativa única, múltipla e texto livre, nessa ordem).
async function processWithBlock() {
  const id = await createProcess();
  await confirmStatement(id);
  await requestBlock(id);
  const [single, multiple, free] = (await settledBlockRequest(id)).blocks[0].questions;
  return { id, single, multiple, free };
}

function answer(id: string, questionId: string, payload: Record<string, unknown>) {
  return testApp.app.inject({
    method: "POST",
    url: `/api/processes/${id}/questions/${questionId}/answer/versions`,
    payload,
  });
}

async function questionOf(id: string, questionId: string) {
  const process = await getProcess(id);
  return process.blocks.flatMap((block: { questions: { id: string }[] }) => block.questions).find(
    (question: { id: string }) => question.id === questionId,
  );
}

describe("Answer", () => {
  it.each([
    ["a single choice", "single", { selectedOptions: [1] }, { selectedOptions: [1], text: null }],
    ["a multiple choice", "multiple", { selectedOptions: [0, 2] }, { selectedOptions: [0, 2], text: null }],
    ["free text", "free", { text: "A diretoria cobrou na última reunião." }, { selectedOptions: null, text: "A diretoria cobrou na última reunião." }],
  ] as const)("to %s is recorded as the first Version", async (_case, which, value, recorded) => {
    const questions = await processWithBlock();
    const question = questions[which];

    const response = await answer(questions.id, question.id, { ...value, basedOnVersionId: null });

    expect(response.statusCode).toBe(201);
    const { answer: saved } = await questionOf(questions.id, question.id);
    expect(saved).toEqual({
      current: { id: response.json().answerVersion.id, number: 1, ...recorded, createdAt: expect.any(String) },
      previous: [],
    });
  });

  it("changed creates a new Version and keeps the previous one", async () => {
    const { id, free } = await processWithBlock();
    const first = (await answer(id, free.id, { text: "Cobrança da diretoria.", basedOnVersionId: null })).json().answerVersion;

    const response = await answer(id, free.id, { text: "Prazo de contrato com cliente.", basedOnVersionId: first.id });

    expect(response.statusCode).toBe(201);
    const { answer: saved } = await questionOf(id, free.id);
    expect(saved.current).toMatchObject({ id: response.json().answerVersion.id, number: 2, text: "Prazo de contrato com cliente." });
    expect(saved.previous).toEqual([{ ...first, text: "Cobrança da diretoria." }]);
  });

  it("changed from a superseded Version is refused, keeping the Version that holds", async () => {
    const { id, single } = await processWithBlock();
    const first = (await answer(id, single.id, { selectedOptions: [0], basedOnVersionId: null })).json().answerVersion;
    // Outra aba altera a resposta a partir da primeira Versão.
    const second = (await answer(id, single.id, { selectedOptions: [1], basedOnVersionId: first.id })).json().answerVersion;

    const response = await answer(id, single.id, { selectedOptions: [2], basedOnVersionId: first.id });

    expect(response.statusCode).toBe(409);
    expect(response.json()).toEqual({ error: "superseded_version" });
    const { answer: saved } = await questionOf(id, single.id);
    expect(saved.current).toMatchObject({ id: second.id, selectedOptions: [1] });
    expect(saved.previous).toHaveLength(1);
  });

  it("given as first answer is refused when the question was answered meanwhile", async () => {
    const { id, multiple } = await processWithBlock();
    await answer(id, multiple.id, { selectedOptions: [0], basedOnVersionId: null });

    const response = await answer(id, multiple.id, { selectedOptions: [1], basedOnVersionId: null });

    expect(response.statusCode).toBe(409);
    expect(response.json()).toEqual({ error: "superseded_version" });
  });

  it.each([
    ["two options to a single choice", "single", { selectedOptions: [0, 1] }],
    ["no option to a single choice", "single", { selectedOptions: [] }],
    ["an option that does not exist", "single", { selectedOptions: [3] }],
    ["no option to a multiple choice", "multiple", { selectedOptions: [] }],
    ["the same option twice", "multiple", { selectedOptions: [1, 1] }],
    ["text to a choice", "multiple", { text: "Atraso nas entregas" }],
    ["options to free text", "free", { selectedOptions: [0] }],
    ["blank text", "free", { text: "  \n " }],
  ] as const)("is refused when giving %s", async (_case, which, value) => {
    const questions = await processWithBlock();

    const response = await answer(questions.id, questions[which].id, { ...value, basedOnVersionId: null });

    expect(response.statusCode).toBe(422);
    expect(response.json()).toEqual({ error: "invalid_answer" });
    expect((await questionOf(questions.id, questions[which].id)).answer).toBeNull();
  });

  it.each([
    ["no value", { basedOnVersionId: null }],
    ["options and text at once", { selectedOptions: [0], text: "Sim", basedOnVersionId: null }],
    ["a negative option", { selectedOptions: [-1], basedOnVersionId: null }],
    ["no base Version", { selectedOptions: [0] }],
    ["a malformed base Version", { selectedOptions: [0], basedOnVersionId: "versao" }],
  ])("is refused when sent with %s", async (_case, payload) => {
    const { id, single } = await processWithBlock();

    const response = await answer(id, single.id, payload);

    expect(response.statusCode).toBe(400);
  });

  it("is refused for a question of another Process", async () => {
    const other = await processWithBlock();
    const id = await createProcess();

    const response = await answer(id, other.single.id, { selectedOptions: [0], basedOnVersionId: null });

    expect(response.statusCode).toBe(404);
    expect(response.json()).toEqual({ error: "question_not_found" });
  });

  it("leaves the Block and its questions as they were presented", async () => {
    const { id, single, free } = await processWithBlock();
    const before = (await getProcess(id)).blocks;

    const first = (await answer(id, single.id, { selectedOptions: [0], basedOnVersionId: null })).json().answerVersion;
    await answer(id, single.id, { selectedOptions: [1], basedOnVersionId: first.id });
    await answer(id, free.id, { text: "Cobrança da diretoria.", basedOnVersionId: null });

    const withoutAnswers = (blocks: { questions: Record<string, unknown>[] }[]) =>
      blocks.map((block) => ({ ...block, questions: block.questions.map(({ answer: _a, draft: _d, ...question }) => question) }));
    expect(withoutAnswers((await getProcess(id)).blocks)).toEqual(withoutAnswers(before));
  });
});

function saveDraft(id: string, questionId: string, payload: Record<string, unknown>) {
  return testApp.app.inject({
    method: "PUT",
    url: `/api/processes/${id}/questions/${questionId}/answer/draft`,
    payload,
  });
}

describe("Draft", () => {
  it("is kept for each question while the user moves between them, and after the Process is reopened", async () => {
    const { id, single, free } = await processWithBlock();

    expect((await saveDraft(id, free.id, { text: "A diretoria co", basedOnVersionId: null })).statusCode).toBe(200);
    expect((await saveDraft(id, single.id, { selectedOptions: [2], basedOnVersionId: null })).statusCode).toBe(200);
    await testApp.close();
    testApp = await createTestApp({ assistant });

    expect((await questionOf(id, free.id)).draft).toEqual({
      basedOnVersionId: null,
      selectedOptions: null,
      text: "A diretoria co",
      updatedAt: expect.any(String),
    });
    expect((await questionOf(id, single.id)).draft).toMatchObject({ selectedOptions: [2], text: null });
    expect((await questionOf(id, free.id)).answer).toBeNull();
  });

  it("keeps only the latest content", async () => {
    const { id, multiple } = await processWithBlock();
    await saveDraft(id, multiple.id, { selectedOptions: [0], basedOnVersionId: null });

    await saveDraft(id, multiple.id, { selectedOptions: [0, 2], basedOnVersionId: null });

    expect((await questionOf(id, multiple.id)).draft).toMatchObject({ selectedOptions: [0, 2] });
  });

  it("may be incomplete", async () => {
    const { id, multiple, free } = await processWithBlock();

    expect((await saveDraft(id, multiple.id, { selectedOptions: [], basedOnVersionId: null })).statusCode).toBe(200);
    expect((await saveDraft(id, free.id, { text: "", basedOnVersionId: null })).statusCode).toBe(200);
  });

  it("keeps the Version the change started from", async () => {
    const { id, free } = await processWithBlock();
    const first = (await answer(id, free.id, { text: "Cobrança da diretoria.", basedOnVersionId: null })).json().answerVersion;

    await saveDraft(id, free.id, { text: "Cobrança da diretoria e prazo", basedOnVersionId: first.id });

    const question = await questionOf(id, free.id);
    expect(question.draft).toMatchObject({ basedOnVersionId: first.id, text: "Cobrança da diretoria e prazo" });
    expect(question.answer.current.text).toBe("Cobrança da diretoria.");
  });

  it("is cleared when the answer is saved as a Version", async () => {
    const { id, free } = await processWithBlock();
    await saveDraft(id, free.id, { text: "Cobrança da diretoria.", basedOnVersionId: null });

    await answer(id, free.id, { text: "Cobrança da diretoria.", basedOnVersionId: null });

    expect((await questionOf(id, free.id)).draft).toBeNull();
  });

  it("stays when saving the answer is refused", async () => {
    const { id, free } = await processWithBlock();
    const first = (await answer(id, free.id, { text: "Cobrança da diretoria.", basedOnVersionId: null })).json().answerVersion;
    await answer(id, free.id, { text: "Prazo de contrato.", basedOnVersionId: first.id });
    await saveDraft(id, free.id, { text: "Escrito na aba antiga.", basedOnVersionId: first.id });

    await answer(id, free.id, { text: "Escrito na aba antiga.", basedOnVersionId: first.id });

    expect((await questionOf(id, free.id)).draft).toMatchObject({ text: "Escrito na aba antiga." });
  });

  it("can be discarded", async () => {
    const { id, free } = await processWithBlock();
    await saveDraft(id, free.id, { text: "Rascunho.", basedOnVersionId: null });

    const response = await testApp.app.inject({
      method: "DELETE",
      url: `/api/processes/${id}/questions/${free.id}/answer/draft`,
    });

    expect(response.statusCode).toBe(204);
    expect((await questionOf(id, free.id)).draft).toBeNull();
  });

  it.each([
    ["text to a choice", "single", { text: "Não sei", basedOnVersionId: null }],
    ["two options to a single choice", "single", { selectedOptions: [0, 1], basedOnVersionId: null }],
    ["an option that does not exist", "multiple", { selectedOptions: [5], basedOnVersionId: null }],
    ["options to free text", "free", { selectedOptions: [0], basedOnVersionId: null }],
    ["a Version of another question", "free", { text: "Texto", basedOnVersionId: "00000000-0000-4000-8000-000000000000" }],
  ] as const)("is refused with %s", async (_case, which, payload) => {
    const questions = await processWithBlock();

    const response = await saveDraft(questions.id, questions[which].id, payload);

    expect(response.statusCode).toBe(422);
    expect((await questionOf(questions.id, questions[which].id)).draft).toBeNull();
  });
});
